### ISSUE TITLE
ChromosomeRegion_AllGenes.tsv datafile missing in datasets

### ISSUE THREAD

**Issue by leilaicruz** [SATAY-LL/SATAY-DOWNSTREAM-ANALYSIS#2]
The datafile ChromosomeRegion_AllGenes.tsv that is used in copareWT1_WT2.py is missing from the dataset folder .

**Comment by leilaicruz** [comment]
Other files missing:
- data_step2_readsWT1.csv
-  data_step2_readsWT2.csv

**Comment by FloorDolsma** [comment]
files are now added
